sudo: false
dist: precise
language: cpp

matrix:
  include:
    - compiler: clang-3.6
      addons:
        apt:
          packages:
            - clang-3.6
            - yasm
            - automake
            - libtool
            - libalut-dev
            - libglu1-mesa-dev
            - xorg-dev
            - autotools-dev
            - cmake
            - cmake-data
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - george-edison55-precise-backports

before_install:
  - echo $TRAVIS_OS_NAME
  - echo $LANG
  - echo $LC_ALL

script:
  - if [ $TRAVIS_OS_NAME == linux ]; then mkdir linux; cd linux; export CC="clang-3.6" CXX="clang++-3.6"; fi
  - cmake ..
  - cd app/tests
  - make -j4 tests
  - if [ $TRAVIS_OS_NAME == linux ]; then export LD_LIBRARY_PATH="./lib"; fi
  - ./tests

after_success:
  - echo "success"
