sudo: required
dist: trusty
language: cpp
compiler:
  - clang
os:
  - linux

before_install:
  - echo $TRAVIS_OS_NAME
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq && sudo apt-get install -y llvm-3.6 llvm-3.6-dev && sudo apt-get install -y cmake; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install libglu1-mesa-dev xorg-dev autotools-dev; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -qq yasm automake libtool libalut-dev; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then wget --no-check-certificate http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then tar -xzf cmake-3.2.3-Linux-x86_64.tar.gz; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo cp -fR cmake-3.2.3-Linux-x86_64/* /usr; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then rm -rf cmake-3.2.3-Linux-x86_64; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then rm cmake-3.2.3-Linux-x86_64.tar.gz; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm && brew install homebrew/versions/cmake30 && brew link --force llvm; fi

install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -qq gcc-5 g++-5; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90; fi

script:
  - if [ $TRAVIS_OS_NAME == linux ]; then mkdir linux; cd linux; fi
  - cmake ..
  - cd app_tests
  - make -j4 tests
  - LD_LIBRARY_PATH=./lib ./tests

after_success:
  - echo "success"

osx_image: xcode61

matrix:
  allow_failures:
    - os: osx
    - os: android
