language: cpp

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq && sudo apt-get install -y llvm-3.4 llvm-3.4-dev && sudo apt-get install -y cmake; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install libglu1-mesa-dev xorg-dev; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -qq yasm; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then wget https://s3.amazonaws.com/biibinaries/thirdparty/cmake-3.0.2-Linux-64.tar.gz; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then tar -xzf cmake-3.0.2-Linux-64.tar.gz; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo cp -fR cmake-3.0.2-Linux-64/* /usr; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then rm -rf cmake-3.0.2-Linux-64; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then rm cmake-3.0.2-Linux-64.tar.gz; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm && brew install homebrew/versions/cmake30 && brew link --force llvm; fi

install:
  - sudo apt-get install -qq gcc-4.8 g++-4.8 
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

script:
  - ./imports/build.sh
  - cmake .
  - cd term
  - make -j4
  - if [ $TRAVIS_OS_NAME == linux ]; then ./pkg/lin.sh; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then ./pkg/macprep.sh && ./pkg/macpkg.sh; fi

after_success:
  - echo "success"

os:
  - linux
  - osx

osx_image: xcode61
