sudo: required
dist: precise
language: cpp

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.6 CC=clang-3.6
      addons:
        apt:
          packages:
            - clang-3.6
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6

before_install:
  - echo $TRAVIS_OS_NAME
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install libglu1-mesa-dev xorg-dev autotools-dev; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -qq yasm automake libtool libalut-dev; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then wget --no-check-certificate http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then tar -xzf cmake-3.2.3-Linux-x86_64.tar.gz; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo cp -fR cmake-3.2.3-Linux-x86_64/* /usr; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then rm -rf cmake-3.2.3-Linux-x86_64; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then rm cmake-3.2.3-Linux-x86_64.tar.gz; fi

script:
  - if [ $TRAVIS_OS_NAME == linux ]; then mkdir linux; cd linux; fi
  - cmake ..
  - cd app_tests
  - make -j4 tests
  - LD_LIBRARY_PATH=./lib ./tests

after_success:
  - echo "success"
