XX("AAPL")  YY("Apple Inc.")
XX("ABT")   YY("Abbott Laboratories")
XX("ACN")   YY("Accenture plc")
XX("AEP")   YY("American Electric Power Co.")
XX("AIG")   YY("American International Group Inc.")
XX("ALL")   YY("Allstate Corp.")
XX("AMGN")  YY("Amgen Inc.")
XX("AMZN")  YY("Amazon.com")
XX("APA")   YY("Apache Corp.")
XX("APC")   YY("Anadarko Petroleum Corporation")
XX("AXP")   YY("American Express Inc.")
XX("BA")    YY("Boeing Co.")
XX("BAC")   YY("Bank of America Corp")
XX("BAX")   YY("Baxter International Inc")
XX("BK")    YY("Bank of New York")
XX("BMY")   YY("Bristol-Myers Squibb")
XX("BRK.B") YY("Berkshire Hathaway")
XX("C")     YY("Citigroup Inc")
XX("CAT")   YY("Caterpillar Inc")
XX("CL")    YY("Colgate-Palmolive Co.")
XX("CMCSA") YY("Comcast Corporation")
XX("COF")   YY("Capital One Financial Corp.")
XX("COP")   YY("ConocoPhillips")
XX("COST")  YY("Costco")
XX("CSCO")  YY("Cisco Systems")
XX("CVS")   YY("CVS Caremark")
XX("CVX")   YY("Chevron")
XX("DD")    YY("DuPont")
XX("DELL")  YY("Dell")
XX("DIS")   YY("The Walt Disney Company")
XX("DOW")   YY("Dow Chemical")
XX("DVN")   YY("Devon Energy")
XX("EBAY")  YY("eBay Inc.")
XX("EMC")   YY("EMC Corporation")
XX("EMR")   YY("Emerson Electric Co.")
XX("EXC")   YY("Exelon")
XX("F")     YY("Ford Motor")
XX("FCX")   YY("Freeport-McMoran")
XX("FDX")   YY("FedEx")
XX("GD")    YY("General Dynamics")
XX("GE")    YY("General Electric Co.")
XX("GILD")  YY("Gilead Sciences")
XX("GM")    YY("General Motors")
XX("GOOG")  YY("Google Inc.")
XX("GS")    YY("Goldman Sachs")
XX("HAL")   YY("Halliburton")
XX("HD")    YY("Home Depot")
XX("HON")   YY("Honeywell")
XX("HPQ")   YY("Hewlett Packard Co")
XX("IBM")   YY("International Business Machines")
XX("INTC")  YY("Intel Corporation")
XX("JNJ")   YY("Johnson & Johnson Inc")
XX("JPM")   YY("JP Morgan Chase & Co")
XX("KO")    YY("The Coca-Cola Company")
XX("LLY")   YY("Eli Lilly and Company")
XX("LMT")   YY("Lockheed-Martin")
XX("LOW")   YY("Lowe's")
XX("MA")    YY("Mastercard Inc")
XX("MCD")   YY("McDonald's Corp")
XX("MDLZ")  YY("Mondelēz International")
XX("MDT")   YY("Medtronic Inc.")
XX("MET")   YY("Metlife Inc.")
XX("MMM")   YY("3M Company")
XX("MO")    YY("Altria Group")
XX("MON")   YY("Monsanto")
XX("MRK")   YY("Merck & Co.")
XX("MS")    YY("Morgan Stanley")
XX("MSFT")  YY("Microsoft")
XX("NKE")   YY("Nike")
XX("NOV")   YY("National Oilwell Varco")
XX("NSC")   YY("Norfolk Southern Corp")
XX("NWSA")  YY("News Corp.")
XX("ORCL")  YY("Oracle Corporation")
XX("OXY")   YY("Occidental Petroleum Corp.")
XX("PEP")   YY("Pepsico Inc.")
XX("PFE")   YY("Pfizer Inc")
XX("PG")    YY("Procter & Gamble Co")
XX("PM")    YY("Phillip Morris International")
XX("QCOM")  YY("Qualcomm Inc.")
XX("RTN")   YY("Raytheon Co (\"NEW\")")
XX("SBUX")  YY("Starbucks Corporation")
XX("SLB")   YY("Schlumberger")
XX("SO")    YY("Southern Company")
XX("SPG")   YY("Simon Property Group, Inc.")
XX("T")     YY("AT&T Inc")
XX("TGT")   YY("Target Corp.")
XX("TWX")   YY("Time Warner Inc.")
XX("TXN")   YY("Texas Instruments")
XX("UNH")   YY("UnitedHealth Group Inc.")
XX("UNP")   YY("Union Pacific Corp.")
XX("UPS")   YY("United Parcel Service Inc")
XX("USB")   YY("US Bancorp")
XX("UTX")   YY("United Technologies Corp")
XX("V")     YY("Visa Inc.")
XX("VZ")    YY("Verizon Communications Inc")
XX("WAG")   YY("Walgreens")
XX("WFC")   YY("Wells Fargo")
XX("WMB")   YY("Williams Companies")
XX("WMT")   YY("Wal-Mart")
XX("XOM")   YY("Exxon Mobil Corp")
