XX("MMM")   YY("3M Company")
XX("ABT")   YY("Abbott Laboratories")
XX("ABBV")  YY("AbbVie")
XX("ANF")   YY("Abercrombie & Fitch Company A")
XX("ACE")   YY("ACE Limited")
XX("ACN")   YY("Accenture plc")
XX("ACT")   YY("Actavis Inc")
XX("ADBE")  YY("Adobe Systems Inc")
XX("ADT")   YY("ADT Corp")
XX("AMD")   YY("Advanced Micro Devices")
XX("AES")   YY("AES Corp")
XX("AET")   YY("Aetna Inc")
XX("AFL")   YY("AFLAC Inc")
XX("A")     YY("Agilent Technologies Inc")
XX("GAS")   YY("AGL Resources Inc.")
XX("APD")   YY("Air Products & Chemicals Inc")
XX("ARG")   YY("Airgas Inc")
XX("AKAM")  YY("Akamai Technologies Inc")
XX("AA")    YY("Alcoa Inc")
XX("ALXN")  YY("Alexion Pharmaceuticals")
XX("ATI")   YY("Allegheny Technologies Inc")
XX("AGN")   YY("Allergan Inc")
XX("ALL")   YY("Allstate Corp")
XX("ALTR")  YY("Altera Corp")
XX("MO")    YY("Altria Group Inc")
XX("AMZN")  YY("Amazon.com Inc")
XX("AEE")   YY("Ameren Corp")
XX("AEP")   YY("American Electric Power")
XX("AXP")   YY("American Express Co")
XX("AIG")   YY("American Intl Group Inc")
XX("AMT")   YY("American Tower Corp A")
XX("AMP")   YY("Ameriprise Financial")
XX("ABC")   YY("AmerisourceBergen Corp")
XX("AMGN")  YY("Amgen Inc")
XX("APH")   YY("Amphenol Corp A")
XX("APC")   YY("Anadarko Petroleum Corp")
XX("ADI")   YY("Analog Devices, Inc.")
XX("AON")   YY("Aon plc")
XX("APA")   YY("Apache Corporation")
XX("AIV")   YY("Apartment Investment & Mgmt")
XX("AAPL")  YY("Apple Inc.")
XX("AMAT")  YY("Applied Materials Inc")
XX("ADM")   YY("Archer-Daniels-Midland Co")
XX("AIZ")   YY("Assurant Inc")
XX("T")     YY("AT&T Inc")
XX("ADSK")  YY("Autodesk Inc")
XX("ADP")   YY("Automatic Data Processing")
XX("AN")    YY("AutoNation Inc")
XX("AZO")   YY("AutoZone Inc")
XX("AVB")   YY("AvalonBay Communities, Inc.")
XX("AVY")   YY("Avery Dennison Corp")
XX("AVP")   YY("Avon Products")
XX("BHI")   YY("Baker Hughes Inc")
XX("BLL")   YY("Ball Corp")
XX("BAC")   YY("Bank of America Corp")
XX("BK")    YY("The Bank of New York Mellon Corp.")
XX("BCR")   YY("Bard (C.R.) Inc.")
XX("BAX")   YY("Baxter International Inc.")
XX("BBT")   YY("BB&T Corporation")
XX("BEAM")  YY("Beam Inc.")
XX("BDX")   YY("Becton Dickinson")
XX("BBBY")  YY("Bed Bath & Beyond")
XX("BMS")   YY("Bemis Company")
XX("BRK.B") YY("Berkshire Hathaway")
XX("BBY")   YY("Best Buy Co. Inc.")
XX("BIIB")  YY("BIOGEN IDEC Inc.")
XX("BLK")   YY("BlackRock")
XX("HRB")   YY("Block H&R")
XX("BA")    YY("Boeing Company")
XX("BWA")   YY("BorgWarner")
XX("BXP")   YY("Boston Properties")
XX("BSX")   YY("Boston Scientific")
XX("BMY")   YY("Bristol-Myers Squibb")
XX("BRCM")  YY("Broadcom Corporation")
XX("BF.B")  YY("Brown-Forman Corporation")
XX("CHRW")  YY("C. H. Robinson Worldwide")
XX("CA")    YY("CA, Inc.")
XX("CVC")   YY("Cablevision Systems Corp.")
XX("COG")   YY("Cabot Oil & Gas")
XX("CAM")   YY("Cameron International Corp.")
XX("CPB")   YY("Campbell Soup")
XX("COF")   YY("Capital One Financial")
XX("CAH")   YY("Cardinal Health Inc.")
XX("CFN")   YY("Carefusion")
XX("KMX")   YY("Carmax Inc")
XX("CCL")   YY("Carnival Corp.")
XX("CAT")   YY("Caterpillar Inc.")
XX("CBG")   YY("CBRE Group")
XX("CBS")   YY("CBS Corp.")
XX("CELG")  YY("Celgene Corp.")
XX("CNP")   YY("CenterPoint Energy")
XX("CTL")   YY("CenturyLink Inc")
XX("CERN")  YY("Cerner")
XX("CF")    YY("CF Industries Holdings Inc")
XX("SCHW")  YY("Charles Schwab")
XX("CHK")   YY("Chesapeake Energy")
XX("CVX")   YY("Chevron Corp.")
XX("CMG")   YY("Chipotle Mexican Grill")
XX("CB")    YY("Chubb Corp.")
XX("CI")    YY("CIGNA Corp.")
XX("CINF")  YY("Cincinnati Financial")
XX("CTAS")  YY("Cintas Corporation")
XX("CSCO")  YY("Cisco Systems")
XX("C")     YY("Citigroup Inc.")
XX("CTXS")  YY("Citrix Systems")
XX("CLF")   YY("Cliffs Natural Resources")
XX("CLX")   YY("The Clorox Company")
XX("CME")   YY("CME Group Inc.")
XX("CMS")   YY("CMS Energy")
XX("COH")   YY("Coach Inc.")
XX("KO")    YY("The Coca Cola Company")
XX("CCE")   YY("Coca-Cola Enterprises")
XX("CTSH")  YY("Cognizant Technology Solutions")
XX("CL")    YY("Colgate-Palmolive")
XX("CMCSA") YY("Comcast Corp.")
XX("CMA")   YY("Comerica Inc.")
XX("CSC")   YY("Computer Sciences Corp.")
XX("CAG")   YY("ConAgra Foods Inc.")
XX("COP")   YY("ConocoPhillips")
XX("CNX")   YY("CONSOL Energy Inc.")
XX("ED")    YY("Consolidated Edison")
XX("STZ")   YY("Constellation Brands")
XX("GLW")   YY("Corning Inc.")
XX("COST")  YY("Costco Co.")
XX("COV")   YY("Covidien plc")
XX("CCI")   YY("Crown Castle International Corp.")
XX("CSX")   YY("CSX Corp.")
XX("CMI")   YY("Cummins Inc.")
XX("CVS")   YY("CVS Caremark Corp.")
XX("DHI")   YY("D. R. Horton")
XX("DHR")   YY("Danaher Corp.")
XX("DRI")   YY("Darden Restaurants")
XX("DVA")   YY("DaVita Inc.")
XX("DE")    YY("Deere & Co.")
XX("DELL")  YY("Dell Inc.")
XX("DLPH")  YY("Delphi Automotive")
XX("DAL")   YY("Delta Air Lines")
XX("DNR")   YY("Denbury Resources Inc.")
XX("XRAY")  YY("Dentsply International")
XX("DVN")   YY("Devon Energy Corp.")
XX("DO")    YY("Diamond Offshore Drilling")
XX("DTV")   YY("DirecTV")
XX("DFS")   YY("Discover Financial Services")
XX("DISCA") YY("Discovery Communications")
XX("DG")    YY("Dollar General")
XX("DLTR")  YY("Dollar Tree")
XX("D")     YY("Dominion Resources")
XX("DOV")   YY("Dover Corp.")
XX("DOW")   YY("Dow Chemical")
XX("DPS")   YY("Dr Pepper Snapple Group")
XX("DTE")   YY("DTE Energy Co.")
XX("DD")    YY("Du Pont (E.I.)")
XX("DUK")   YY("Duke Energy")
XX("DNB")   YY("Dun & Bradstreet")
XX("ETFC")  YY("E-Trade")
XX("EMN")   YY("Eastman Chemical")
XX("ETN")   YY("Eaton Corp.")
XX("EBAY")  YY("eBay Inc.")
XX("ECL")   YY("Ecolab Inc.")
XX("EIX")   YY("Edison Int'l")
XX("EW")    YY("Edwards Lifesciences")
XX("EA")    YY("Electronic Arts")
XX("EMC")   YY("EMC Corp.")
XX("EMR")   YY("Emerson Electric")
XX("ESV")   YY("Ensco plc")
XX("ETR")   YY("Entergy Corp.")
XX("EOG")   YY("EOG Resources")
XX("EQT")   YY("EQT Corporation")
XX("EFX")   YY("Equifax Inc.")
XX("EQR")   YY("Equity Residential")
XX("EL")    YY("Estee Lauder Cos.")
XX("EXC")   YY("Exelon Corp.")
XX("EXPE")  YY("Expedia Inc.")
XX("EXPD")  YY("Expeditors Int'l")
XX("ESRX")  YY("Express Scripts")
XX("XOM")   YY("Exxon Mobil Corp.")
XX("FFIV")  YY("F5 Networks")
XX("FDO")   YY("Family Dollar Stores")
XX("FAST")  YY("Fastenal Co")
XX("FDX")   YY("FedEx Corporation")
XX("FIS")   YY("Fidelity National Information Services")
XX("FITB")  YY("Fifth Third Bancorp")
XX("FSLR")  YY("First Solar Inc")
XX("FE")    YY("FirstEnergy Corp")
XX("FISV")  YY("Fiserv Inc")
XX("FLIR")  YY("FLIR Systems")
XX("FLS")   YY("Flowserve Corporation")
XX("FLR")   YY("Fluor Corp.")
XX("FMC")   YY("FMC Corporation")
XX("FTI")   YY("FMC Technologies Inc.")
XX("F")     YY("Ford Motor")
XX("FRX")   YY("Forest Laboratories")
XX("FOSL")  YY("Fossil, Inc.")
XX("BEN")   YY("Franklin Resources")
XX("FCX")   YY("Freeport-McMoran Cp & Gld")
XX("FTR")   YY("Frontier Communications")
XX("GME")   YY("GameStop Corp.")
XX("GCI")   YY("Gannett Co.")
XX("GPS")   YY("Gap (The)")
XX("GRMN")  YY("Garmin Ltd.")
XX("GD")    YY("General Dynamics")
XX("GE")    YY("General Electric")
XX("GIS")   YY("General Mills")
XX("GM")    YY("General Motors")
XX("GPC")   YY("Genuine Parts")
XX("GNW")   YY("Genworth Financial Inc.")
XX("GILD")  YY("Gilead Sciences")
XX("GS")    YY("Goldman Sachs Group")
XX("GT")    YY("Goodyear Tire & Rubber")
XX("GOOG")  YY("Google Inc.")
XX("GWW")   YY("Grainger (W.W.) Inc.")
XX("HAL")   YY("Halliburton Co.")
XX("HOG")   YY("Harley-Davidson")
XX("HAR")   YY("Harman Int'l Industries")
XX("HRS")   YY("Harris Corporation")
XX("HIG")   YY("Hartford Financial Svc.Gp.")
XX("HAS")   YY("Hasbro Inc.")
XX("HCP")   YY("HCP Inc.")
XX("HCN")   YY("Health Care REIT")
XX("HP")    YY("Helmerich & Payne")
XX("HES")   YY("Hess Corporation")
XX("HPQ")   YY("Hewlett-Packard")
XX("HD")    YY("Home Depot")
XX("HON")   YY("Honeywell Int'l Inc.")
XX("HRL")   YY("Hormel Foods Corp.")
XX("HSP")   YY("Hospira Inc.")
XX("HST")   YY("Host Hotels & Resorts")
XX("HCBK")  YY("Hudson City Bancorp")
XX("HUM")   YY("Humana Inc.")
XX("HBAN")  YY("Huntington Bancshares")
XX("ITW")   YY("Illinois Tool Works")
XX("IR")    YY("Ingersoll-Rand PLC")
XX("TEG")   YY("Integrys Energy Group Inc.")
XX("INTC")  YY("Intel Corp.")
XX("ICE")   YY("IntercontinentalExchange Inc.")
XX("IBM")   YY("International Bus. Machines")
XX("IGT")   YY("International Game Technology")
XX("IP")    YY("International Paper")
XX("IPG")   YY("Interpublic Group")
XX("IFF")   YY("Intl Flavors & Fragrances")
XX("INTU")  YY("Intuit Inc.")
XX("ISRG")  YY("Intuitive Surgical Inc.")
XX("IVZ")   YY("Invesco Ltd.")
XX("IRM")   YY("Iron Mountain Incorporated")
XX("JBL")   YY("Jabil Circuit")
XX("JEC")   YY("Jacobs Engineering Group")
XX("JDSU")  YY("JDS Uniphase Corp.")
XX("JNJ")   YY("Johnson & Johnson")
XX("JCI")   YY("Johnson Controls")
XX("JOY")   YY("Joy Global Inc.")
XX("JPM")   YY("JPMorgan Chase & Co.")
XX("JNPR")  YY("Juniper Networks")
XX("KSU")   YY("Kansas City Southern")
XX("K")     YY("Kellogg Co.")
XX("KEY")   YY("KeyCorp")
XX("KMB")   YY("Kimberly-Clark")
XX("KIM")   YY("Kimco Realty")
XX("KMI")   YY("Kinder Morgan")
XX("KLAC")  YY("KLA-Tencor Corp.")
XX("KSS")   YY("Kohl's Corp.")
XX("KRFT")  YY("Kraft Foods Group")
XX("KR")    YY("Kroger Co.")
XX("LTD")   YY("L Brands Inc.")
XX("LLL")   YY("L-3 Communications Holdings")
XX("LH")    YY("Laboratory Corp. of America Holding")
XX("LRCX")  YY("Lam Research")
XX("LM")    YY("Legg Mason")
XX("LEG")   YY("Leggett & Platt")
XX("LEN")   YY("Lennar Corp.")
XX("LUK")   YY("Leucadia National Corp.")
XX("LIFE")  YY("Life Technologies")
XX("LLY")   YY("Lilly (Eli) & Co.")
XX("LNC")   YY("Lincoln National")
XX("LLTC")  YY("Linear Technology Corp.")
XX("LMT")   YY("Lockheed Martin Corp.")
XX("L")     YY("Loews Corp.")
XX("LO")    YY("Lorillard Inc.")
XX("LOW")   YY("Lowe's Cos.")
XX("LSI")   YY("LSI Corporation")
XX("LYB")   YY("LyondellBasell")
XX("MTB")   YY("M&T Bank Corp.")
XX("MAC")   YY("Macerich")
XX("M")     YY("Macy's Inc.")
XX("MRO")   YY("Marathon Oil Corp.")
XX("MPC")   YY("Marathon Petroleum")
XX("MAR")   YY("Marriott Int'l.")
XX("MMC")   YY("Marsh & McLennan")
XX("MAS")   YY("Masco Corp.")
XX("MA")    YY("Mastercard Inc.")
XX("MAT")   YY("Mattel Inc.")
XX("MKC")   YY("McCormick & Co.")
XX("MCD")   YY("McDonald's Corp.")
XX("MHFI")  YY("McGraw Hill Financial")
XX("MCK")   YY("McKesson Corp.")
XX("MJN")   YY("Mead Johnson")
XX("MWV")   YY("MeadWestvaco Corporation")
XX("MDT")   YY("Medtronic Inc.")
XX("MRK")   YY("Merck & Co.")
XX("MET")   YY("MetLife Inc.")
XX("MCHP")  YY("Microchip Technology")
XX("MU")    YY("Micron Technology")
XX("MSFT")  YY("Microsoft Corp.")
XX("MOLX")  YY("Molex Inc.")
XX("TAP")   YY("Molson Coors Brewing Company")
XX("MDLZ")  YY("Mondelez International")
XX("MON")   YY("Monsanto Co.")
XX("MNST")  YY("Monster Beverage")
XX("MCO")   YY("Moody's Corp")
XX("MS")    YY("Morgan Stanley")
XX("MOS")   YY("The Mosaic Company")
XX("MSI")   YY("Motorola Solutions Inc.")
XX("MUR")   YY("Murphy Oil")
XX("MYL")   YY("Mylan Inc.")
XX("NBR")   YY("Nabors Industries Ltd.")
XX("NDAQ")  YY("NASDAQ OMX Group")
XX("NOV")   YY("National Oilwell Varco Inc.")
XX("NTAP")  YY("NetApp")
XX("NFLX")  YY("NetFlix Inc.")
XX("NWL")   YY("Newell Rubbermaid Co.")
XX("NFX")   YY("Newfield Exploration Co")
XX("NEM")   YY("Newmont Mining Corp. (Hldg. Co.)")
XX("NWSA")  YY("News Corporation")
XX("NEE")   YY("NextEra Energy Resources")
XX("NLSN")  YY("Nielsen Holdings")
XX("NKE")   YY("NIKE Inc.")
XX("NI")    YY("NiSource Inc.")
XX("NE")    YY("Noble Corp")
XX("NBL")   YY("Noble Energy Inc")
XX("JWN")   YY("Nordstrom")
XX("NSC")   YY("Norfolk Southern Corp.")
XX("NTRS")  YY("Northern Trust Corp.")
XX("NOC")   YY("Northrop Grumman Corp.")
XX("NU")    YY("Northeast Utilities")
XX("NRG")   YY("NRG Energy")
XX("NUE")   YY("Nucor Corp.")
XX("NVDA")  YY("Nvidia Corporation")
XX("NYX")   YY("NYSE Euronext")
XX("ORLY")  YY("O'Reilly Automotive")
XX("OXY")   YY("Occidental Petroleum")
XX("OMC")   YY("Omnicom Group")
XX("OKE")   YY("ONEOK")
XX("ORCL")  YY("Oracle Corp.")
XX("OI")    YY("Owens-Illinois Inc")
XX("PCG")   YY("P G & E Corp.")
XX("PCAR")  YY("PACCAR Inc.")
XX("PLL")   YY("Pall Corp.")
XX("PH")    YY("Parker-Hannifin")
XX("PDCO")  YY("Patterson Companies")
XX("PAYX")  YY("Paychex Inc.")
XX("BTU")   YY("Peabody Energy")
XX("JCP")   YY("Penney (J.C.)")
XX("PNR")   YY("Pentair Ltd.")
XX("PBCT")  YY("People's United Bank")
XX("POM")   YY("Pepco Holdings Inc.")
XX("PEP")   YY("PepsiCo Inc.")
XX("PKI")   YY("PerkinElmer")
XX("PRGO")  YY("Perrigo")
XX("PETM")  YY("PetSmart, Inc.")
XX("PFE")   YY("Pfizer Inc.")
XX("PM")    YY("Philip Morris International")
XX("PSX")   YY("Phillips 66")
XX("PNW")   YY("Pinnacle West Capital")
XX("PXD")   YY("Pioneer Natural Resources")
XX("PBI")   YY("Pitney-Bowes")
XX("PCL")   YY("Plum Creek Timber Co.")
XX("PNC")   YY("PNC Financial Services")
XX("RL")    YY("Polo Ralph Lauren Corp.")
XX("PPG")   YY("PPG Industries")
XX("PPL")   YY("PPL Corp.")
XX("PX")    YY("Praxair Inc.")
XX("PCP")   YY("Precision Castparts")
XX("PCLN")  YY("Priceline.com Inc")
XX("PFG")   YY("Principal Financial Group")
XX("PG")    YY("Procter & Gamble")
XX("PGR")   YY("Progressive Corp.")
XX("PLD")   YY("Prologis")
XX("PRU")   YY("Prudential Financial")
XX("PEG")   YY("Public Serv. Enterprise Inc.")
XX("PSA")   YY("Public Storage")
XX("PHM")   YY("Pulte Homes Inc.")
XX("PVH")   YY("PVH Corp.")
XX("QEP")   YY("QEP Resources")
XX("PWR")   YY("Quanta Services Inc.")
XX("QCOM")  YY("QUALCOMM Inc.")
XX("DGX")   YY("Quest Diagnostics")
XX("RRC")   YY("Range Resources Corp.")
XX("RTN")   YY("Raytheon Co.")
XX("RHT")   YY("Red Hat Inc.")
XX("REGN")  YY("Regeneron")
XX("RF")    YY("Regions Financial Corp.")
XX("RSG")   YY("Republic Services Inc")
XX("RAI")   YY("Reynolds American Inc.")
XX("RHI")   YY("Robert Half International")
XX("ROK")   YY("Rockwell Automation Inc.")
XX("COL")   YY("Rockwell Collins")
XX("ROP")   YY("Roper Industries")
XX("ROST")  YY("Ross Stores")
XX("RDC")   YY("Rowan Cos.")
XX("R")     YY("Ryder System")
XX("SWY")   YY("Safeway Inc.")
XX("SAIC")  YY("SAIC")
XX("CRM")   YY("Salesforce.com")
XX("SNDK")  YY("SanDisk Corporation")
XX("SCG")   YY("SCANA Corp")
XX("SLB")   YY("Schlumberger Ltd.")
XX("SNI")   YY("Scripps Networks Interactive Inc.")
XX("STX")   YY("Seagate Technology")
XX("SEE")   YY("Sealed Air Corp.(New)")
XX("SRE")   YY("Sempra Energy")
XX("SHW")   YY("Sherwin-Williams")
XX("SIAL")  YY("Sigma-Aldrich")
XX("SPG")   YY("Simon Property Group Inc")
XX("SLM")   YY("SLM Corporation")
XX("SJM")   YY("Smucker (J.M.)")
XX("SNA")   YY("Snap-On Inc.")
XX("SO")    YY("Southern Co.")
XX("LUV")   YY("Southwest Airlines")
XX("SWN")   YY("Southwestern Energy")
XX("SE")    YY("Spectra Energy Corp.")
XX("STJ")   YY("St Jude Medical")
XX("SWK")   YY("Stanley Black & Decker")
XX("SPLS")  YY("Staples Inc.")
XX("SBUX")  YY("Starbucks Corp.")
XX("HOT")   YY("Starwood Hotels & Resorts")
XX("STT")   YY("State Street Corp.")
XX("SRCL")  YY("Stericycle Inc")
XX("SYK")   YY("Stryker Corp.")
XX("STI")   YY("SunTrust Banks")
XX("SYMC")  YY("Symantec Corp.")
XX("SYY")   YY("Sysco Corp.")
XX("TROW")  YY("T. Rowe Price Group")
XX("TGT")   YY("Target Corp.")
XX("TEL")   YY("TE Connectivity Ltd.")
XX("TE")    YY("TECO Energy")
XX("THC")   YY("Tenet Healthcare Corp.")
XX("TDC")   YY("Teradata Corp.")
XX("TER")   YY("Teradyne Inc.")
XX("TSO")   YY("Tesoro Petroleum Co.")
XX("TXN")   YY("Texas Instruments")
XX("TXT")   YY("Textron Inc.")
XX("HSY")   YY("The Hershey Company")
XX("TRV")   YY("The Travelers Companies Inc.")
XX("TMO")   YY("Thermo Fisher Scientific")
XX("TIF")   YY("Tiffany & Co.")
XX("TWX")   YY("Time Warner Inc.")
XX("TWC")   YY("Time Warner Cable Inc.")
XX("TJX")   YY("TJX Companies Inc.")
XX("TMK")   YY("Torchmark Corp.")
XX("TSS")   YY("Total System Services")
XX("TRIP")  YY("TripAdvisor")
XX("FOXA")  YY("Twenty-First Century Fox")
XX("TSN")   YY("Tyson Foods")
XX("TYC")   YY("Tyco International")
XX("USB")   YY("U.S. Bancorp")
XX("UNP")   YY("Union Pacific")
XX("UNH")   YY("United Health Group Inc.")
XX("UPS")   YY("United Parcel Service")
XX("X")     YY("United States Steel Corp.")
XX("UTX")   YY("United Technologies")
XX("UNM")   YY("Unum Group")
XX("URBN")  YY("Urban Outfitters")
XX("VFC")   YY("V.F. Corp.")
XX("VLO")   YY("Valero Energy")
XX("VAR")   YY("Varian Medical Systems")
XX("VTR")   YY("Ventas Inc")
XX("VRSN")  YY("Verisign Inc.")
XX("VZ")    YY("Verizon Communications")
XX("VIAB")  YY("Viacom Inc.")
XX("V")     YY("Visa Inc.")
XX("VNO")   YY("Vornado Realty Trust")
XX("VMC")   YY("Vulcan Materials")
XX("WMT")   YY("Wal-Mart Stores")
XX("WAG")   YY("Walgreen Co.")
XX("DIS")   YY("The Walt Disney Company")
XX("WPO")   YY("Washington Post Co B")
XX("WM")    YY("Waste Management Inc.")
XX("WAT")   YY("Waters Corporation")
XX("WLP")   YY("WellPoint Inc.")
XX("WFC")   YY("Wells Fargo")
XX("WDC")   YY("Western Digital")
XX("WU")    YY("Western Union Co")
XX("WY")    YY("Weyerhaeuser Corp.")
XX("WHR")   YY("Whirlpool Corp.")
XX("WFM")   YY("Whole Foods Market")
XX("WMB")   YY("Williams Cos.")
XX("WIN")   YY("Windstream Communications")
XX("WEC")   YY("Wisconsin Energy Corporation")
XX("WPX")   YY("WPX Energy, Inc.")
XX("WYN")   YY("Wyndham Worldwide")
XX("WYNN")  YY("Wynn Resorts Ltd")
XX("XEL")   YY("Xcel Energy Inc")
XX("XRX")   YY("Xerox Corp.")
XX("XLNX")  YY("Xilinx Inc")
XX("XL")    YY("XL Capital")
XX("XYL")   YY("Xylem Inc.")
XX("YHOO")  YY("Yahoo Inc.")
XX("YUM")   YY("Yum! Brands Inc")
XX("ZMH")   YY("Zimmer Holdings")
XX("ZION")  YY("Zions Bancorp")
XX("ZTS")   YY("Zoetis")
