set(LFL_ANDROID 1)
set(LFL_ANDROID_SDK "$ENV{HOME}/android-sdk-macosx" CACHE PATH "Android SDK path")
set(LFL_ANDROID_NDK "$ENV{HOME}/android-ndk-r13b" CACHE PATH "Android NDK path")
set(LFL_ANDROID_ROOT "$ENV{HOME}/android-toolchain" CACHE PATH "Android toolchain path")
set(LFL_GRADLE_BIN "$ENV{HOME}/gradle-2.4/bin/gradle" CACHE PATH "Gradle path")

#include(core/CMake/LFLOS.cmake)
if(NOT LFL_OS)
  if(APPLE)
    set(LFL_OS osx)
  elseif(UNIX)
    set(LFL_OS linux)
  elseif(WIN32 OR WIN64)
    set(LFL_OS win32)
  else()
    MESSAGE(FATAL_ERROR "unknown OS")
  endif()
endif()

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_C_COMPILER ${LFL_ANDROID_ROOT}/bin/arm-linux-androideabi-gcc CACHE PATH "C compiler")
set(CMAKE_CXX_COMPILER ${LFL_ANDROID_ROOT}/bin/arm-linux-androideabi-g++ CACHE PATH "C++ compiler")
set(CMAKE_AR ${LFL_ANDROID_ROOT}/bin/arm-linux-androideabi-ar CACHE PATH "archive")
set(CMAKE_RANLIB ${LFL_ANDROID_ROOT}/bin/arm-linux-androideabi-ranlib CACHE PATH "ranlib")
set(CMAKE_LINKER ${LFL_ANDROID_ROOT}/bin/arm-linux-androideabi-ld CACHE PATH "linker")

set(ENV_CC "${LFL_ANDROID_ROOT}/bin/arm-linux-androideabi-gcc")
set(ENV_CXX "${LFL_ANDROID_ROOT}/bin/arm-linux-androideabi-g++")
set(ENV_CPP "${LFL_ANDROID_ROOT}/bin/arm-linux-androideabi-cpp")
set(ENV_CXXCPP "${LFL_ANDROID_ROOT}/bin/arm-linux-androideabi-cpp")
set(ENV_AR "${LFL_ANDROID_ROOT}/bin/arm-linux-androideabi-ar")
set(ENV_RANLIB "${LFL_ANDROID_ROOT}/bin/arm-linux-androideabi-ranlib")
set(ENV_CFLAGS "-isysroot ${LFL_ANDROID_ROOT}/sysroot")
set(ENV_CXXFLAGS "-isysroot ${LFL_ANDROID_ROOT}/sysroot")
set(ENV_LDFLAGS "-isysroot ${LFL_ANDROID_ROOT}/sysroot")
set(CONFIGURE_OPTIONS "--host=arm")
set(CONFIGURE_ENV CC=${ENV_CC} CXX=${ENV_CXX} CPP=${ENV_CPP} CXXCPP=${ENV_CXXCPP} AR=${ENV_AR} RANLIB=${ENV_RANLIB}
    CFLAGS=${ENV_CFLAGS} CXXFLAGS=${ENV_CXXFLAGS} LDFLAGS=${ENV_LDFLAGS})

set(C_LIBRARY ${LFL_ANDROID_ROOT}/sysroot/usr/lib/libc.so)
set(M_LIBRARY ${LFL_ANDROID_ROOT}/sysroot/usr/lib/libm.so)
set(ZLIB_INCLUDE_DIR ${LFL_ANDROID_ROOT}/sysroot/usr/include)
set(ZLIB_LIBRARY ${LFL_ANDROID_ROOT}/sysroot/usr/lib/libz.so)
