set(LFL_IPHONE 1)
if(LFL_IPHONESIM)
 set(IPHONEROOT "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer")
 set(IPHONESDK "${IPHONEROOT}/SDKs/iPhoneSimulator8.3.sdk")
else(LFL_IPHONESIM)
 set(IPHONEROOT "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer")
 set(IPHONESDK "${IPHONEROOT}/SDKs/iPhoneOS8.3.sdk")
endif()

include(CMakeForceCompiler)
CMAKE_FORCE_C_COMPILER(/usr/bin/clang Apple)
CMAKE_FORCE_CXX_COMPILER(/usr/bin/clang++ Apple)
set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_AR ar CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER_WORKS TRUE)
set(CMAKE_C_COMPILER_WORKS TRUE)
set(CMAKE_OSX_SYSROOT ${IPHONESDK} CACHE PATH "iOS sysroot")
set(CMAKE_OSX_DEPLOYMENT_TARGET "" CACHE STRING "iOS deploy" FORCE)
set(CMAKE_SYSTEM_FRAMEWORK_PATH ${IPHONESDK}/System/Library/Frameworks)
if(LFL_IPHONESIM)
set(CMAKE_OSX_ARCHITECTURES i386 CACHE string "iOS arch")
else(LFL_IPHONESIM)
set(CMAKE_OSX_ARCHITECTURES armv7 CACHE string "iOS arch")
endif()

if(LFL_IPHONESIM)
 add_definitions("-isysroot ${IPHONESDK} -mmacosx-version-min=10.5 -D__IPHONE_OS_VERSION_MIN_REQUIRED=30200")
 set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -isysroot ${IPHONESDK} -mmacosx-version-min=10.5 -F${IPHONESDK}/System/Library/Frameworks")
else(LFL_IPHONESIM)
 add_definitions("-isysroot ${IPHONESDK} -miphoneos-version-min=5.0 -D__IPHONE_OS_VERSION_MIN_REQUIRED=50000")
 set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -isysroot ${IPHONESDK} -miphoneos-version-min=5.0 -F${IPHONESDK}/System/Library/Frameworks")
endif(LFL_IPHONESIM)

include_directories(${IPHONESDK}/System/Library/Frameworks/OpenGLES.framework/Headers/ ${IPHONESDK}/System/Library/Frameworks/Foundation.framework/Headers/ ${IPHONESDK}/System/Library/Frameworks/UIKit.framework/Headers/)

set(ENV{CC} "/usr/bin/clang")
set(ENV{CXX} "/usr/bin/clang++")
set(ENV{AR} "${IPHONEROOT}/usr/bin/ar")
set(ENV{CODESIGN_ALLOCATE} "${IPHONEROOT}/usr/bin/codesign_allocate")
if(LFL_IPHONESIM)
set(ENV{CFLAGS} "-arch i686 -mmacosx-version-min=10.5 -I${IPHONESDK}/usr/include/ -isysroot ${IPHONESDK}")
set(ENV{CXXFLAGS} "-arch i686 -mmacosx-version-min=10.5 -I${IPHONESDK}/usr/include/ -isysroot ${IPHONESDK}")
set(ENV{LDFLAGS} "-arch i686 -isysroot ${IPHONESDK} -mmacosx-version-min=10.5")
else(LFL_IPHONESIM)
set(CONFIGURE_OPTIONS "--host=arm-apple-darwin")
set(ENV{CFLAGS} "-arch armv7 -miphoneos-version-min=5.0 -isysroot ${IPHONESDK}")
set(ENV{CXXFLAGS} "-arch armv7 -miphoneos-version-min=5.0 -isysroot ${IPHONESDK}")
set(ENV{LDFLAGS} "-arch armv7 -isysroot ${IPHONESDK} -miphoneos-version-min=5.0")
endif(LFL_IPHONESIM)
