if(LFL_IPHONESIM)
 set(IPHONESIM "-Simulator")
endif(LFL_IPHONESIM)
set(LFL_IPHONE 1)

if(IPHONESIM)
 set(IPHONEROOT "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer")
 set(IPHONESDK "${IPHONEROOT}/SDKs/iPhoneSimulator8.3.sdk")
else(IPHONESIM)
 set(IPHONEROOT "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer")
 set(IPHONESDK "${IPHONEROOT}/SDKs/iPhoneOS8.3.sdk")
endif()

include(CMakeForceCompiler)
CMAKE_FORCE_C_COMPILER(/usr/bin/clang Apple)
CMAKE_FORCE_CXX_COMPILER(/usr/bin/clang++ Apple)
set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_AR ar CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER_WORKS TRUE)
set(CMAKE_C_COMPILER_WORKS TRUE)
set(CMAKE_OSX_SYSROOT ${IPHONESDK} CACHE PATH "iOS sysroot")
set(CMAKE_OSX_DEPLOYMENT_TARGET "" CACHE STRING "iOS deploy" FORCE)
set(CMAKE_SYSTEM_FRAMEWORK_PATH ${IPHONESDK}/System/Library/Frameworks)
if(IPHONESIM)
set(CMAKE_OSX_ARCHITECTURES i386 CACHE string "iOS arch")
else(IPHONESIM)
set(CMAKE_OSX_ARCHITECTURES armv7 CACHE string "iOS arch")
endif()

if(IPHONESIM)
 add_definitions("-isysroot ${IPHONESDK} -mmacosx-version-min=10.5 -D__IPHONE_OS_VERSION_MIN_REQUIRED=30200")
 set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -isysroot ${IPHONESDK} -mmacosx-version-min=10.5 -F${IPHONESDK}/System/Library/Frameworks")
else(IPHONESIM)
 add_definitions("-isysroot ${IPHONESDK} -miphoneos-version-min=5.0 -D__IPHONE_OS_VERSION_MIN_REQUIRED=50000")
 set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -isysroot ${IPHONESDK} -miphoneos-version-min=5.0 -F${IPHONESDK}/System/Library/Frameworks")
endif(IPHONESIM)

include_directories(${IPHONESDK}/System/Library/Frameworks/OpenGLES.framework/Headers/ ${IPHONESDK}/System/Library/Frameworks/Foundation.framework/Headers/ ${IPHONESDK}/System/Library/Frameworks/UIKit.framework/Headers/)

macro(lfl_export_toolchain)
set(ENV{CC} "/usr/bin/clang")
set(ENV{CXX} "/usr/bin/clang++")
set(ENV{AR} "${IPHONEROOT}/usr/bin/ar")
if(IPHONESIM)
set(CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS} --enable-static=yes --enable-shared=no")
set(ENV{CFLAGS} "-arch i686 -pipe -mdynamic-no-pic -std=c99 -Wno-trigraphs -fpascal-strings -fasm-blocks -O0 -Wreturn-type -Wunused-variable -fmessage-length=0 -fvisibility=hidden -mmacosx-version-min=10.5 -I${IPHONESDK}/usr/include/ -isysroot ${IPHONESDK}")
set(ENV{LDFLAGS} "-arch i686 -isysroot ${IPHONESDK} -Wl,-dead_strip -mmacosx-version-min=10.5")
else(IPHONESIM)
set(CONFIGURE_OPTIONS "${CONFIGURE_OPTIONS} --host=arm-apple-darwin --enable-static=yes --enable-shared=no")
set(ENV{CFLAGS} "-arch armv7 -pipe -mdynamic-no-pic -std=c99 -Wno-trigraphs -fpascal-strings -O0 -Wreturn-type -Wunused-variable -fmessage-length=0 -fvisibility=hidden -miphoneos-version-min=2.0 -gdwarf-2 -mthumb -I${IPHONESDK}/usr/include/libxml2 -isysroot ${IPHONESDK}")
set(ENV{LDFLAGS} "-arch armv7 -isysroot ${IPHONESDK} -Wl,-dead_strip -miphoneos-version-min=5.0")
endif(IPHONESIM)
endmacro(lfl_export_toolchain)
