set(LFL_APPLE_DEVELOPER "/Applications/Xcode.app/Contents/Developer")

#set(CMAKE_OSX_ARCHITECTURES i686 CACHE string "arch")
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

set(OSX_VERSION_MIN "-mmacosx-version-min=10.9")

if(CMAKE_GENERATOR MATCHES Xcode)
  set(LFL_XCODE TRUE)
  set(CMAKE_SIZEOF_VOID_P 8)
else()
  set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${OSX_VERSION_MIN}")
  add_definitions("${OSX_VERSION_MIN}")
endif()

set(ENV_CFLAGS   "${OSX_VERSION_MIN}")
set(ENV_CXXFLAGS "${OSX_VERSION_MIN}")
set(ENV_LDFLAGS  "${OSX_VERSION_MIN}")
set(CONFIGURE_ENV CFLAGS=${ENV_CFLAGS} CXXFLAGS=${ENV_CXXFLAGS} LDFLAGS=${ENV_LDFLAGS})
